# Generated by Django 5.2.17 on 2026-08-31 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('checking', 'Cuenta corriente'), ('savings', 'Ahorro'), ('credit', 'Tarjeta de credito'), ('cash', 'Efectivo')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('visibility', models.CharField(choices=[('shared', 'Compartida'), ('private', 'Privada')], default='shared', max_length=10)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('billing_cycle_day', models.PositiveSmallIntegerField(blank=True, help_text='Dia del mes de fecha de corte (tarjetas)', null=True)),
                ('payment_due_day', models.PositiveSmallIntegerField(blank=True, help_text='Dia del mes de fecha limite de pago (tarjetas)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Solo aplica si visibility=private', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('visibility', models.CharField(choices=[('shared', 'Compartida'), ('private', 'Privada')], default='shared', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('a_favor', 'A favor'), ('en_contra', 'En contra')], max_length=10)),
                ('person', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_settled', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
