# Generated by Django 5.2.17 on 2026-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_absorb_asset_liability_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='billing_cycle_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes de fecha de corte (tarjetas)', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes de fecha límite de pago (tarjetas)', null=True),
        ),
    ]
