# Generated by Django 5.2.17 on 2026-09-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_wallet_billing_cycle_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='kind',
            field=models.CharField(choices=[('bank', 'Cuenta bancaria'), ('credit', 'Crédito'), ('cash', 'Efectivo'), ('custom', 'Personalizada')], default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
