# Generated by Django 5.2.17 on 2026-09-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_wallet_options_wallet_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
