# Generated by Django 5.2.17 on 2026-09-05 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_wallet_color"),
        ("email_import", "0003_alter_emailimportlog_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="bank_schema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallets",
                to="email_import.bankemailschema",
            ),
        ),
    ]
