# Generated by Django 5.2.17 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_wallet_bank_schema"),
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="card_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallets",
                to="loyalty.cardproduct",
            ),
        ),
    ]
