# Generated by Django 5.2.17 on 2026-09-09 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_wallet_card_product"),
        ("loyalty", "0002_alter_bank_options_alter_cardproduct_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="card_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Sólo tarjetas de crédito -- se define en el admin (Loyalty → Productos de tarjeta).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallets",
                to="loyalty.cardproduct",
                verbose_name="producto de tarjeta",
            ),
        ),
    ]
