# Generated by Django 5.2.17 on 2026-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_wallet_card_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="low_balance_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
