# Generated by Django 5.2.17 on 2026-09-13 01:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_wallet_low_balance_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last4', models.CharField(max_length=4, verbose_name='últimos 4 dígitos')),
                ('label', models.CharField(blank=True, help_text='Para identificar el plástico, p. ej. "Adicional -- María".', max_length=50, verbose_name='etiqueta (opcional)')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_cards', to='accounts.wallet')),
            ],
            options={
                'verbose_name': 'tarjeta adicional',
                'verbose_name_plural': 'tarjetas adicionales',
                'ordering': ['label', 'last4'],
                'constraints': [models.UniqueConstraint(fields=('wallet', 'last4'), name='unique_extra_last4_per_wallet')],
            },
        ),
    ]
