# Generated by Django 5.2.17 on 2026-09-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_backfill_wallet_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="savings_interest_compounding",
            field=models.CharField(
                choices=[
                    ("daily", "Diaria"),
                    ("biweekly", "Quincenal"),
                    ("monthly", "Mensual"),
                    ("annual", "Anual"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="savings_interest_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="savings_interest_rate_period",
            field=models.CharField(
                choices=[("monthly", "Mensual"), ("annual", "Anual")],
                default="annual",
                max_length=10,
            ),
        ),
    ]
