# Generated by Django 5.2.17 on 2026-09-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_wallet_savings_interest_compounding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="min_payment_floor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto mínimo fijo (tarjetas)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="min_payment_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="% del saldo al corte (tarjetas)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
