# Generated by Django 5.2.17 on 2026-09-13 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, help_text='Bajada corta para la pantalla de upgrade (opcional).')),
                ('is_default', models.BooleanField(default=False, help_text='El plan que recibe un usuario sin suscripción vigente. Debe haber exactamente uno.')),
                ('max_workspaces_owned', models.PositiveIntegerField(blank=True, help_text='Workspaces que este usuario puede poseer como owner.', null=True)),
                ('max_members_per_workspace', models.PositiveIntegerField(blank=True, help_text='Miembros (incluido el owner) por workspace de este plan.', null=True)),
                ('max_active_recurring', models.PositiveIntegerField(blank=True, help_text='Recurrentes activos por workspace de este plan.', null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual'), ('lifetime', 'De por vida')], max_length=10)),
                ('amount_cents', models.PositiveIntegerField(help_text='Precio en centavos, p. ej. 1999 = 19.99.')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('external_refs', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.plan')),
            ],
            options={
                'ordering': ('plan', 'billing_period'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('active', 'Activa'), ('past_due', 'Pago vencido'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=12)),
                ('provider', models.CharField(choices=[('manual', 'Manual (otorgado por admin)'), ('wompi', 'Wompi')], default='manual', max_length=20)),
                ('checkout_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_customer_id', models.CharField(blank=True, max_length=120)),
                ('external_subscription_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Vacío = no vence (alta manual sin fecha, o plan de por vida).', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Uso interno -- p. ej. motivo de un alta manual.')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('plan_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.planprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(fields=('plan', 'billing_period', 'currency'), name='unique_price_per_plan_period_currency'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='billing_sub_user_id_fe5b98_idx'),
        ),
    ]
