# Generated by Django 5.2.17 on 2026-09-17 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_promocode_promocoderedemption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="trial_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Días de prueba gratis de este plan sin pasar por el proveedor de pago (ver `services.start_trial`). Vacío o 0 = sin prueba gratis.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(
                default=False,
                help_text="Otorgada por `services.start_trial` (Plan.trial_days), no por pago ni código de invitación. Un usuario sólo puede tener una en toda su vida.",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_trial", True)),
                fields=("user",),
                name="one_trial_subscription_per_user",
            ),
        ),
    ]
