# Generated by Django 5.2.17 on 2026-09-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_eventos_de_webhook_procesados'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewal_notice_sent_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
