# Generated by Django 5.2.17 on 2026-09-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_renewal_notice_sent_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='prorated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='proration_credit_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
