# Generated by Django 5.2.17 on 2026-09-23 01:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_subscription_proration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, help_text='Correo, @usuario, teléfono...', max_length=200)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=20, help_text='Porcentaje de cada pago de sus referidos, p. ej. 20 = 20 %.', max_digits=5)),
                ('commission_months', models.PositiveIntegerField(blank=True, default=6, help_text='Durante cuántos meses desde el primer pago de cada referido se paga comisión. Vacío = siempre.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactivo: sus códigos siguen dando el beneficio, pero no generan comisión nueva.')),
                ('notes', models.TextField(blank=True, help_text='Uso interno -- acuerdo, forma de pago...')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='affiliate',
            field=models.ForeignKey(blank=True, help_text='Código de un influencer: quien lo use (o llegue por su enlace ?ref=CÓDIGO) queda atribuido a él.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promo_codes', to='billing.affiliate'),
        ),
        migrations.CreateModel(
            name='AffiliateReferral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('link', 'Enlace (?ref=)'), ('code', 'Código canjeado')], max_length=10)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='billing.affiliate')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='billing.promocode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(blank=True, max_length=120)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commission_cents', models.PositiveIntegerField(default=0)),
                ('commission_paid_at', models.DateTimeField(blank=True, help_text='Cuándo se le pagó esta comisión al afiliado.', null=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.affiliate')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-paid_at',),
                'indexes': [models.Index(fields=['affiliate', 'commission_paid_at'], name='billing_pay_affilia_761a07_idx')],
            },
        ),
    ]
