# Generated by Django 5.2.17 on 2026-09-08 23:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0016_installments_statement_only"),
        ("workspaces", "0004_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CardProduct",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "American Express"),
                            ("other", "Otra"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="loyalty.bank",
                    ),
                ),
            ],
            options={
                "ordering": ["bank__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("points", "Puntos"),
                            ("cashback", "Cashback"),
                            ("discount", "Descuento"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "point_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "card_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="loyalty.cardproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["card_product", "kind"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyEarning",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("points", "Puntos"),
                            ("cashback", "Cashback"),
                            ("discount", "Descuento"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_earnings",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_earnings",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyCategoryRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "category_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="loyalty.categorytype",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_rates",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cardproduct",
            constraint=models.UniqueConstraint(
                fields=("bank", "name"), name="unique_product_per_bank"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltyearning",
            constraint=models.UniqueConstraint(
                fields=("transaction", "program"),
                name="unique_earning_per_transaction_program",
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltycategoryrate",
            constraint=models.UniqueConstraint(
                fields=("program", "category_type"),
                name="unique_rate_per_program_category",
            ),
        ),
    ]
