# Generated by Django 5.2.17 on 2026-09-09 02:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={
                "ordering": ["name"],
                "verbose_name": "banco",
                "verbose_name_plural": "bancos",
            },
        ),
        migrations.AlterModelOptions(
            name="cardproduct",
            options={
                "ordering": ["bank__name", "name"],
                "verbose_name": "producto de tarjeta",
                "verbose_name_plural": "productos de tarjeta",
            },
        ),
        migrations.AlterModelOptions(
            name="categorytype",
            options={
                "ordering": ["name"],
                "verbose_name": "rubro",
                "verbose_name_plural": "rubros",
            },
        ),
        migrations.AlterModelOptions(
            name="loyaltycategoryrate",
            options={
                "verbose_name": "tasa por rubro",
                "verbose_name_plural": "tasas por rubro",
            },
        ),
        migrations.AlterModelOptions(
            name="loyaltyearning",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ganancia de lealtad",
                "verbose_name_plural": "ganancias de lealtad",
            },
        ),
        migrations.AlterModelOptions(
            name="loyaltyprogram",
            options={
                "ordering": ["card_product", "kind"],
                "verbose_name": "programa de lealtad",
                "verbose_name_plural": "programas de lealtad",
            },
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="cardproduct",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="loyalty.bank",
                verbose_name="banco",
            ),
        ),
        migrations.AlterField(
            model_name="cardproduct",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="cardproduct",
            name="network",
            field=models.CharField(
                choices=[
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("amex", "American Express"),
                    ("other", "Otra"),
                ],
                default="other",
                max_length=12,
                verbose_name="red",
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ícono (emoji, opcional)"
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="loyaltycategoryrate",
            name="category_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="loyalty.categorytype",
                verbose_name="rubro",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltycategoryrate",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_rates",
                to="loyalty.loyaltyprogram",
                verbose_name="programa",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltycategoryrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Mismo formato que la tasa default del programa (puntos por unidad, o fracción para cashback/descuento). Reemplaza la default sólo para este rubro.",
                max_digits=6,
                verbose_name="tasa",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyprogram",
            name="card_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="loyalty.cardproduct",
                verbose_name="producto de tarjeta",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyprogram",
            name="default_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text='Puntos: puntos ganados por unidad de moneda gastada (p. ej. 2 = "2 puntos por dólar"). Cashback/descuento: fracción del monto (0.01 = 1%, 0.05 = 5%). Se usa para cualquier rubro que no tenga una tasa especial en "Tasas por rubro" (abajo, guardando primero).',
                max_digits=6,
                verbose_name="tasa default",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyprogram",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="loyaltyprogram",
            name="kind",
            field=models.CharField(
                choices=[
                    ("points", "Puntos"),
                    ("cashback", "Cashback"),
                    ("discount", "Descuento"),
                ],
                max_length=10,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyprogram",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Para identificarlo si un producto tiene más de un programa del mismo tipo.",
                max_length=100,
                verbose_name="nombre (opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyprogram",
            name="point_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Sólo puntos: valor estimado por punto (p. ej. 0.01 = 1 punto vale 1 centavo). Sólo referencia, no afecta ningún cálculo real.",
                max_digits=8,
                null=True,
                verbose_name="valor de canje por punto (opcional)",
            ),
        ),
    ]
