# Generated by Django 5.2.17 on 2026-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_bank_options_alter_cardproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loyaltycategoryrate',
            name='unique_rate_per_program_category',
        ),
        migrations.AddField(
            model_name='loyaltycategoryrate',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Si se indica, la tasa sólo aplica las compras hechas ese día (p. ej. 2 puntos los lunes en Supermercado). Vacío = todos los días. Gana a la tasa del rubro sin día.', null=True, verbose_name='día de la semana (opcional)'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('weekday__isnull', False)), fields=('program', 'category_type', 'weekday'), name='unique_rate_per_program_category_weekday'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('weekday__isnull', True)), fields=('program', 'category_type'), name='unique_rate_per_program_category'),
        ),
    ]
