# Generated by Django 5.2.17 on 2026-09-20 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_rate_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('aliases', models.TextField(blank=True, help_text='Cómo aparece en la descripción de una transacción, uno por línea (sin importar mayúsculas ni tildes). Cuenta si aparece como palabra completa: "mc" reconoce "mc combo" pero no "mcdonalds".', verbose_name='alias')),
            ],
            options={
                'verbose_name': 'comercio',
                'verbose_name_plural': 'comercios',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='loyaltycategoryrate',
            options={'verbose_name': 'tasa por rubro o comercio', 'verbose_name_plural': 'tasas por rubro o comercio'},
        ),
        migrations.RemoveConstraint(
            model_name='loyaltycategoryrate',
            name='unique_rate_per_program_category_weekday',
        ),
        migrations.RemoveConstraint(
            model_name='loyaltycategoryrate',
            name='unique_rate_per_program_category',
        ),
        migrations.AlterField(
            model_name='loyaltycategoryrate',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loyalty.categorytype', verbose_name='rubro'),
        ),
        migrations.AlterField(
            model_name='loyaltycategoryrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Mismo formato que la tasa default del programa (puntos por unidad, o fracción para cashback/descuento). Reemplaza la default sólo para este rubro o comercio.', max_digits=6, verbose_name='tasa'),
        ),
        migrations.AlterField(
            model_name='loyaltycategoryrate',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Si se indica, la tasa sólo aplica las compras hechas ese día (p. ej. 2 puntos los lunes en Supermercado). Vacío = todos los días. Gana a la tasa sin día.', null=True, verbose_name='día de la semana (opcional)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='category_type',
            field=models.ForeignKey(blank=True, help_text='Vacío si el comercio no encaja en ningún rubro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='loyalty.categorytype', verbose_name='rubro'),
        ),
        migrations.AddField(
            model_name='loyaltycategoryrate',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Para un beneficio de un solo comercio. Se llena éste **o** el rubro, no los dos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loyalty.merchant', verbose_name='comercio'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category_type__isnull', False), ('merchant__isnull', True)), models.Q(('category_type__isnull', True), ('merchant__isnull', False)), _connector='OR'), name='rate_has_category_type_xor_merchant'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('category_type__isnull', False), ('weekday__isnull', False)), fields=('program', 'category_type', 'weekday'), name='unique_rate_per_program_category_weekday'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('category_type__isnull', False), ('weekday__isnull', True)), fields=('program', 'category_type'), name='unique_rate_per_program_category'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant__isnull', False), ('weekday__isnull', False)), fields=('program', 'merchant', 'weekday'), name='unique_rate_per_program_merchant_weekday'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant__isnull', False), ('weekday__isnull', True)), fields=('program', 'merchant'), name='unique_rate_per_program_merchant'),
        ),
    ]
