# Generated by Django 5.2.17 on 2026-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_merchants'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loyaltycategoryrate',
            name='unique_rate_per_program_category_weekday',
        ),
        migrations.RemoveConstraint(
            model_name='loyaltycategoryrate',
            name='unique_rate_per_program_category',
        ),
        migrations.RemoveConstraint(
            model_name='loyaltycategoryrate',
            name='unique_rate_per_program_merchant_weekday',
        ),
        migrations.RemoveConstraint(
            model_name='loyaltycategoryrate',
            name='unique_rate_per_program_merchant',
        ),
        migrations.AddField(
            model_name='loyaltycategoryrate',
            name='requires_autopay',
            field=models.BooleanField(default=False, help_text='La tasa aplica únicamente si el gasto es un cargo automático de la tarjeta (Pagos Automáticos de servicios): el gasto lo marca así al registrarlo.', verbose_name='sólo cargos automáticos'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sólo las compras de este monto o más ganan (p. ej. 10 = "a partir de $10"). Vacío = cualquier monto. Aplica a puntos y cashback; el descuento lo aplica el propio cliente al registrar el gasto.', max_digits=14, null=True, verbose_name='compra mínima (opcional)'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('category_type__isnull', False), ('weekday__isnull', False)), fields=('program', 'category_type', 'weekday', 'requires_autopay'), name='unique_rate_per_program_category_weekday'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('category_type__isnull', False), ('weekday__isnull', True)), fields=('program', 'category_type', 'requires_autopay'), name='unique_rate_per_program_category'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant__isnull', False), ('weekday__isnull', False)), fields=('program', 'merchant', 'weekday', 'requires_autopay'), name='unique_rate_per_program_merchant_weekday'),
        ),
        migrations.AddConstraint(
            model_name='loyaltycategoryrate',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant__isnull', False), ('weekday__isnull', True)), fields=('program', 'merchant', 'requires_autopay'), name='unique_rate_per_program_merchant'),
        ),
    ]
