# Generated by Django 5.2.17 on 2026-09-20 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_wallet_savings_interest_compounding_and_more'),
        ('loyalty', '0005_min_amount_autopay'),
        ('transactions', '0030_transaction_merchant'),
        ('workspaces', '0005_budget_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('redeem', 'Canje'), ('adjust', 'Ajuste')], max_length=10)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='loyalty.loyaltyprogram')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_movements', to='accounts.wallet')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_movements', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'movimiento de recompensas',
                'verbose_name_plural': 'movimientos de recompensas',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='loyalty_movement_delta_not_zero'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'redeem'), _negated=True), ('delta__lt', 0), _connector='OR'), name='loyalty_redeem_is_negative')],
            },
        ),
    ]
