# Generated by Django 5.2.17 on 2026-08-31 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankEmailSchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=100, unique=True)),
                ('sender_pattern', models.CharField(help_text='Dominio o patron de remitente que identifica a este banco', max_length=255)),
                ('parser_version', models.CharField(default='v1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailImportLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmar'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('failed', 'Fallo de parseo')], default='pending', max_length=20)),
                ('raw_email_subject', models.CharField(blank=True, max_length=255)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('extracted_merchant', models.CharField(blank=True, max_length=255)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_import_logs', to='accounts.account')),
                ('bank_schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='email_import.bankemailschema')),
                ('resulting_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_log', to='transactions.transaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_import_logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
