# Generated by Django 5.2.17 on 2026-09-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_wallet_billing_cycle_day_and_more'),
        ('email_import', '0002_rename_account_fk_to_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailimportlog',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_import_logs', to='accounts.wallet'),
        ),
    ]
