# Generated by Django 5.2.17 on 2026-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_import", "0003_alter_emailimportlog_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailimportlog",
            name="raw_email_body",
            field=models.TextField(blank=True, default=""),
        ),
    ]