# Generated by Django 5.2.17 on 2026-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0004_emailimportlog_raw_email_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailimportlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de confirmar'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('failed', 'Fallo de parseo'), ('auto_handled', 'Resuelto automaticamente')], default='pending', max_length=20),
        ),
    ]
