# Generated by Django 5.2.17 on 2026-08-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('email_import', 'Importada por correo'), ('recurring', 'Gasto recurrente'), ('installment', 'Cuota de compra a plazo')], default='manual', max_length=20),
        ),
    ]
