# Generated by Django 5.2.17 on 2026-09-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_wallet_billing_cycle_day_and_more'),
        ('transactions', '0004_rename_account_fk_to_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpurchase',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_purchases', to='accounts.wallet'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='accounts.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='accounts.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet'),
        ),
    ]
