# Generated by Django 5.2.17 on 2026-09-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_installmentpurchase_wallet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Cada semana'), ('biweekly', 'Cada dos semanas'), ('every_3_weeks', 'Cada tres semanas'), ('every_4_weeks', 'Cada cuatro semanas'), ('monthly', 'Cada mes'), ('every_2_months', 'Cada dos meses'), ('every_3_months', 'Cada tres meses'), ('every_4_months', 'Cada cuatro meses'), ('every_6_months', 'Cada seis meses'), ('yearly', 'Cada año')], default='monthly', max_length=16),
        ),
    ]
