# Generated by Django 5.2.17 on 2026-09-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_wallet_color'),
        ('transactions', '0006_alter_category_options_category_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpurchase',
            name='payment_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installment_payments', to='accounts.wallet'),
        ),
    ]
