# Generated by Django 5.2.17 on 2026-09-05 03:44

import apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_installmentpurchase_payment_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.transactions.models.receipt_upload_path,
            ),
        ),
    ]
