# Generated by Django 5.2.17 on 2026-09-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_transaction_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("email_import", "Importada por correo"),
                    ("recurring", "Gasto recurrente"),
                    ("installment", "Cuota de compra a plazo"),
                    ("quick_add", "Alta rápida (Atajo)"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
