# Generated by Django 5.2.17 on 2026-09-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_backfill_transaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="split_group",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
