# Generated by Django 5.2.17 on 2026-09-05 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_wallet_color"),
        ("transactions", "0011_transaction_split_group"),
        ("workspaces", "0003_workspace_base_currency_exchangerate"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSuggestionDismissal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("approx_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="transactions.category",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.wallet",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_dismissals",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "category", "wallet", "approx_amount"),
                        name="unique_recurring_suggestion_dismissal",
                    )
                ],
            },
        ),
    ]
