# Generated by Django 5.2.17 on 2026-09-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0013_tag_transaction_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
