# Generated by Django 5.2.17 on 2026-09-07 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0014_recurring_expense_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="installment_purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="transactions.installmentpurchase",
            ),
        ),
    ]
