# Generated by Django 5.2.17 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
        ("transactions", "0017_installmentpurchase_drop_legacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="loyalty.categorytype",
            ),
        ),
    ]
