# Generated by Django 5.2.17 on 2026-09-09 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0002_alter_bank_options_alter_cardproduct_options_and_more"),
        ("transactions", "0018_category_category_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional -- se define en el admin (Loyalty → Rubros).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="loyalty.categorytype",
                verbose_name="rubro para tarjetas con recompensas",
            ),
        ),
    ]
