# Generated by Django 5.2.17 on 2026-09-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_wallet_card_product"),
        ("transactions", "0020_alter_transaction_source"),
        ("workspaces", "0004_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="to_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_recurring_transfers",
                to="accounts.wallet",
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Ingreso"),
                    ("expense", "Gasto"),
                    ("transfer", "Transferencia"),
                ],
                default="expense",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_expenses",
                to="transactions.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["income", "expense", "transfer"])),
                name="recurring_expense_type_valid",
            ),
        ),
    ]
