# Generated by Django 5.2.17 on 2026-09-09 15:53

import apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0022_backfill_recurring_expense_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.transactions.models.receipt_upload_path,
            ),
        ),
    ]
