# Generated by Django 5.2.17 on 2026-09-17 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0027_transaction_is_refundable_transaction_is_refunded_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="refund_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_transactions",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("email_import", "Importada por correo"),
                    ("recurring", "Gasto recurrente"),
                    ("installment", "Cuota de compra a plazo"),
                    ("quick_add", "Alta rápida (Atajo)"),
                    ("excel_import", "Importada de Excel"),
                    ("refund", "Reembolso registrado"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
