# Generated by Django 5.2.17 on 2026-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_transaction_refund_of_alter_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_autopay',
            field=models.BooleanField(default=False, verbose_name='cargo automático'),
        ),
    ]
