# Generated by Django 5.2.17 on 2026-09-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_min_amount_autopay'),
        ('transactions', '0029_transaction_is_autopay'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loyalty.merchant', verbose_name='comercio'),
        ),
    ]
