# Generated by Django 5.2.17 on 2026-09-20 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_wallet_savings_interest_compounding_and_more'),
        ('loyalty', '0006_movements'),
        ('transactions', '0030_transaction_merchant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-date'], name='txn_wallet_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_wallet', '-date'], name='txn_towallet_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', '-date'], name='txn_category_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='txn_date_idx'),
        ),
    ]
