# Generated by Django 5.2.17 on 2026-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModuleFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text='Clave estable que usa el código para preguntar (p. ej. "ai", "email_import", "excel_import"). No se traduce ni se muestra.',
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nombre para reconocerlo en esta lista.",
                        max_length=100,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "disabled_message",
                    models.TextField(
                        blank=True,
                        help_text="Lo que ve la persona mientras está apagado. Vacío = mensaje genérico.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "interruptor de módulo",
                "verbose_name_plural": "interruptores de módulos",
                "ordering": ["key"],
            },
        ),
    ]
