# Generated by Django 5.2.17 on 2026-09-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo_url",
            field=models.URLField(
                blank=True, default="", verbose_name="foto de perfil"
            ),
        ),
    ]
