# Generated by Django 5.2.17 on 2026-09-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_linked",
            field=models.BooleanField(
                default=False, verbose_name="cuenta de Google vinculada"
            ),
        ),
    ]
