# Generated by Django 5.2.17 on 2026-09-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_twofactorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=True, verbose_name='tour de bienvenida completado'),
        ),
    ]
