# Generated by Django 5.2.17 on 2026-09-05 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_inbound_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="base_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("currency", models.CharField(max_length=3)),
                ("rate_to_base", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["currency"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "currency"),
                        name="unique_rate_per_currency",
                    )
                ],
            },
        ),
    ]
