# Generated by Django 5.2.17 on 2026-09-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0005_budget_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("receipt", "Lectura de recibo"),
                            ("parse", "Parseo de texto o voz"),
                            ("chat", "Pregunta de chat"),
                            ("summary", "Resumen mensual"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Modelo de Gemini que atendió la llamada.",
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Respondió"), ("error", "Falló")],
                        default="ok",
                        max_length=8,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cost_micros", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("counts_against_quota", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "consumo de IA",
                "verbose_name_plural": "consumos de IA",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "operation", "created_at"],
                        name="ai_aiusage_user_id_8a58a3_idx",
                    )
                ],
            },
        ),
    ]
