# Generated by Django 5.2.17 on 2026-10-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='operation',
            field=models.CharField(choices=[('receipt', 'Lectura de recibo'), ('parse', 'Parseo de texto o voz'), ('chat', 'Pregunta de chat'), ('summary', 'Resumen mensual'), ('statement', 'Lectura de estado de cuenta')], max_length=16),
        ),
    ]
