# Generated by Django 5.2.17 on 2026-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="remind_low_balance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="statement_due_days_before",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="warn_statement_due",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("recurring_due", "Recurrente por vencer"),
                    ("installment_due", "Cuota por vencer"),
                    ("budget_threshold", "Presupuesto por agotarse"),
                    ("low_balance", "Saldo bajo"),
                    ("statement_due", "Estado de cuenta por vencer"),
                ],
                max_length=20,
            ),
        ),
    ]
