# Generated by Django 5.2.17 on 2026-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreference_remind_low_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushdevice",
            name="auth",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="p256dh",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pushdevice",
            name="token",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
