# Generated by Django 5.2.17 on 2026-09-13 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushdevice_auth_pushdevice_p256dh_and_more'),
        ('workspaces', '0004_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('invitation', 'Invitación a un presupuesto'), ('email_import_pending', 'Correo bancario por revisar'), ('recurring_due', 'Recurrente por vencer'), ('installment_due', 'Cuota por vencer'), ('budget_threshold', 'Presupuesto por agotarse'), ('low_balance', 'Saldo bajo'), ('statement_due', 'Estado de cuenta por vencer')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unread', 'No leída'), ('read', 'Leída'), ('resolved', 'Resuelta')], default='unread', max_length=10)),
                ('related_object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx')],
            },
        ),
    ]
