# Generated by Django 5.2.17 on 2026-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_subscription_notification_kinds"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="warn_monthly_summary",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("invitation", "Invitación a un presupuesto"),
                    ("email_import_pending", "Correo bancario por revisar"),
                    ("subscription_renewal_due", "Suscripción por vencer"),
                    ("subscription_expired", "Suscripción vencida"),
                    ("recurring_due", "Recurrente por vencer"),
                    ("installment_due", "Cuota por vencer"),
                    ("budget_threshold", "Presupuesto por agotarse"),
                    ("low_balance", "Saldo bajo"),
                    ("statement_due", "Estado de cuenta por vencer"),
                    ("insight", "Patrón de gasto detectado"),
                    ("monthly_summary", "Resumen mensual"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("recurring_due", "Recurrente por vencer"),
                    ("installment_due", "Cuota por vencer"),
                    ("budget_threshold", "Presupuesto por agotarse"),
                    ("low_balance", "Saldo bajo"),
                    ("statement_due", "Estado de cuenta por vencer"),
                    ("insight", "Patrón de gasto detectado"),
                    ("monthly_summary", "Resumen mensual"),
                ],
                max_length=20,
            ),
        ),
    ]
